[package]
name = "tcp_chunker"
version = "0.1.0"
authors = ["Jack <jack.mead@foreveroceans.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
byteorder = "1.3.4"
